// Generated by hypequery
// This file defines TypeScript types based on your ClickHouse database schema

export interface IntrospectedSchema {
  trips: {
    'trip_id': 'UInt32';
    'pickup_datetime': 'DateTime';
    'dropoff_datetime': 'DateTime';
    'pickup_longitude': 'Nullable(Float64)';
    'pickup_latitude': 'Nullable(Float64)';
    'dropoff_longitude': 'Nullable(Float64)';
    'dropoff_latitude': 'Nullable(Float64)';
    'passenger_count': 'UInt8';
    'trip_distance': 'Float32';
    'fare_amount': 'Float32';
    'extra': 'Float32';
    'tip_amount': 'Float32';
    'tolls_amount': 'Float32';
    'total_amount': 'Float32';
    'payment_type': 'Enum8(\'CSH\' = 1, \'CRE\' = 2, \'NOC\' = 3, \'DIS\' = 4, \'UNK\' = 5)';
    'pickup_ntaname': 'LowCardinality(String)';
    'dropoff_ntaname': 'LowCardinality(String)';
    'tags': 'Array(String)';
  };
}

// Type-safe record types for each table
export interface TripsRecord {
  'trip_id': number;
  'pickup_datetime': string;
  'dropoff_datetime': string;
  'pickup_longitude': number | null;
  'pickup_latitude': number | null;
  'dropoff_longitude': number | null;
  'dropoff_latitude': number | null;
  'passenger_count': number;
  'trip_distance': number;
  'fare_amount': number;
  'extra': number;
  'tip_amount': number;
  'tolls_amount': number;
  'total_amount': number;
  'payment_type': string;
  'pickup_ntaname': string;
  'dropoff_ntaname': string;
  'tags': Array<string>;
}

