// Generated by hypequery (manually seeded for the example)
// This file defines TypeScript types based on your ClickHouse database schema

export interface IntrospectedSchema {
  'analytics.tenants': {
    tenant_id: 'String';
    name: 'String';
    plan: 'String';
  };
  'analytics.users': {
    id: 'UUID';
    tenant_id: 'String';
    region: 'LowCardinality(String)';
    status: 'LowCardinality(String)';
    last_active: 'DateTime';
    mrr: 'Float64';
  };
}

export interface TenantsRecord {
  tenant_id: string;
  name: string;
  plan: string;
}

export interface UsersRecord {
  id: string;
  tenant_id: string;
  region: string;
  status: string;
  last_active: string;
  mrr: number;
}
